# Generated by Django 4.1.7 on 2023-02-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(default=True, max_length=255, null=True, upload_to='')),
                ('url', models.URLField()),
            ],
        ),
    ]
