# Generated by Django 4.1.7 on 2023-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='formid',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
    ]
